[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1 pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1 pnpm run build"]

[start]
cmd = "pnpm start"

