/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RwaSymbolRouteImport } from './routes/rwa/$symbol'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin/unauthorized'
import { Route as AdminTokenLaunchRouteImport } from './routes/admin/token-launch'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RwaSymbolRoute = RwaSymbolRouteImport.update({
  id: '/rwa/$symbol',
  path: '/rwa/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/admin/unauthorized',
  path: '/admin/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTokenLaunchRoute = AdminTokenLaunchRouteImport.update({
  id: '/admin/token-launch',
  path: '/admin/token-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drops': typeof DropsRoute
  '/portfolio': typeof PortfolioRoute
  '/status': typeof StatusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/token-launch': typeof AdminTokenLaunchRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/rwa/$symbol': typeof RwaSymbolRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drops': typeof DropsRoute
  '/portfolio': typeof PortfolioRoute
  '/status': typeof StatusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/token-launch': typeof AdminTokenLaunchRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/rwa/$symbol': typeof RwaSymbolRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drops': typeof DropsRoute
  '/portfolio': typeof PortfolioRoute
  '/status': typeof StatusRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/token-launch': typeof AdminTokenLaunchRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/rwa/$symbol': typeof RwaSymbolRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drops'
    | '/portfolio'
    | '/status'
    | '/admin/login'
    | '/admin/token-launch'
    | '/admin/unauthorized'
    | '/rwa/$symbol'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drops'
    | '/portfolio'
    | '/status'
    | '/admin/login'
    | '/admin/token-launch'
    | '/admin/unauthorized'
    | '/rwa/$symbol'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/drops'
    | '/portfolio'
    | '/status'
    | '/admin/login'
    | '/admin/token-launch'
    | '/admin/unauthorized'
    | '/rwa/$symbol'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DropsRoute: typeof DropsRoute
  PortfolioRoute: typeof PortfolioRoute
  StatusRoute: typeof StatusRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTokenLaunchRoute: typeof AdminTokenLaunchRoute
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  RwaSymbolRoute: typeof RwaSymbolRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rwa/$symbol': {
      id: '/rwa/$symbol'
      path: '/rwa/$symbol'
      fullPath: '/rwa/$symbol'
      preLoaderRoute: typeof RwaSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unauthorized': {
      id: '/admin/unauthorized'
      path: '/admin/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/token-launch': {
      id: '/admin/token-launch'
      path: '/admin/token-launch'
      fullPath: '/admin/token-launch'
      preLoaderRoute: typeof AdminTokenLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DropsRoute: DropsRoute,
  PortfolioRoute: PortfolioRoute,
  StatusRoute: StatusRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTokenLaunchRoute: AdminTokenLaunchRoute,
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  RwaSymbolRoute: RwaSymbolRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
