/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RwaSymbolRouteImport } from './routes/rwa/$symbol'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RwaSymbolRoute = RwaSymbolRouteImport.update({
  id: '/rwa/$symbol',
  path: '/rwa/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/drops': typeof DropsRoute
  '/portfolio': typeof PortfolioRoute
  '/status': typeof StatusRoute
  '/rwa/$symbol': typeof RwaSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/drops': typeof DropsRoute
  '/portfolio': typeof PortfolioRoute
  '/status': typeof StatusRoute
  '/rwa/$symbol': typeof RwaSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/drops': typeof DropsRoute
  '/portfolio': typeof PortfolioRoute
  '/status': typeof StatusRoute
  '/rwa/$symbol': typeof RwaSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/drops'
    | '/portfolio'
    | '/status'
    | '/rwa/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apply' | '/drops' | '/portfolio' | '/status' | '/rwa/$symbol'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/drops'
    | '/portfolio'
    | '/status'
    | '/rwa/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  DropsRoute: typeof DropsRoute
  PortfolioRoute: typeof PortfolioRoute
  StatusRoute: typeof StatusRoute
  RwaSymbolRoute: typeof RwaSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rwa/$symbol': {
      id: '/rwa/$symbol'
      path: '/rwa/$symbol'
      fullPath: '/rwa/$symbol'
      preLoaderRoute: typeof RwaSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  DropsRoute: DropsRoute,
  PortfolioRoute: PortfolioRoute,
  StatusRoute: StatusRoute,
  RwaSymbolRoute: RwaSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
