import { NextResponse } from 'next/server';

export async function GET() {
  const baseUrl = process.env.NEXT_PUBLIC_URL || 'https://aces.fun';
  const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'https://acesbackend-production.up.railway.app';

  const manifest = {
    accountAssociation: {
      header:
        'eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4NjYwYzg3MzNDZGExM2QyNTZCNDQwRjQxNTg3YTdBOWYzYUVFMDM2MiJ9',
      payload: 'eyJkb21haW4iOiJhY2VzLmZ1biJ9',
      signature:
        'AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABASHtxVZ1JvxB0S0AkYwGz8mhAxnC5X6UY86Co6iFS3-JAcIcyNZMG2KEvzFDmohsPcqFwmbYhHSjWlOH56W1_OwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAA-FIQshzFAwL0d7pWaG0gGdybZ63hWwqMROytRWUz0BEOrSzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABxjQ_y618U4g0Tp6qG7jE5Xt1DwZoysMnpTZsjz7nMapqFzHxSGSHhnoR7HgcrcC08kzM-7jQtNRN7thBLG4NhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiSUZjb2tmUnhOV3g5NEtYTG0xYXZsdkNBeU91MmhGT08zOXF5a2I2QzRpUSIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSS',
    },
    miniapp: {
      version: '1',
      name: 'ACES.fun',
      homeUrl: baseUrl,
      iconUrl: `${baseUrl}/aces-preview-logo.png`,
      splashImageUrl: `${baseUrl}/aces-preview-logo.png`,
      splashBackgroundColor: '#000000',
      webhookUrl: `${apiUrl}/api/v1/farcaster/webhook`,
      subtitle: 'Trade Tokenized Collectibles',
      description:
        'Trade tokenized real-world collectibles on Base. Buy, sell, and trade unique tokenized assets.',
      screenshotUrls: [
        'https://aces.fun/screenshots/shot-1.webp',
        'https://aces.fun/screenshots/shot-2.webp',
        'https://aces.fun/screenshots/shot-3.webp',
      ],
      primaryCategory: 'social',
      tags: ['collectibles', 'trading', 'base', 'rwa', 'tokenization'],
      heroImageUrl: `${baseUrl}/aces-preview-logo.png`,
      tagline: 'Trade Tokenized Collectibles',
      ogTitle: 'ACES.fun',
      ogDescription: 'Trade Tokenized Collectibles on Base',
      ogImageUrl: `${baseUrl}/aces-preview-logo.png`,
      noindex: false,
    },
  };

  return NextResponse.json(manifest, {
    headers: {
      'Cache-Control': 's-maxage=300, stale-while-revalidate=600',
    },
  });
}
